spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/main_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

app:
  minio:
    endpoint: http://minio:9000
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
    public-base-url: http://localhost:9000
    bucket: game-content
    secure: false

  publications:
    page-size-default: 10
    page-size-max: 50