ALTER TABLE heroes
    ADD COLUMN base_power INTEGER;

CREATE TABLE hero_tag_groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(100) NOT NULL UNIQUE,
    name_json  JSONB        NOT NULL,
    description_json JSONB,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE hero_tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT       NOT NULL REFERENCES hero_tag_groups (id),
    code       VARCHAR(100) NOT NULL UNIQUE,
    name_json  JSONB        NOT NULL,
    description_json JSONB,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_hero_tags_group_id
    ON hero_tags (group_id);

CREATE TABLE heroes_tags
(
    hero_id BIGINT NOT NULL REFERENCES heroes (id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES hero_tags (id),
    PRIMARY KEY (hero_id, tag_id)
);

CREATE INDEX idx_heroes_tags_tag_id
    ON heroes_tags (tag_id);
