CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    slug VARCHAR(150) NOT NULL UNIQUE,
    name_json JSONB NOT NULL,
    description_json JSONB,
    image_bucket VARCHAR(255),
    image_object_key VARCHAR(1024),
    status VARCHAR(30) NOT NULL,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE event_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    name_json JSONB NOT NULL,
    description_json JSONB,
    image_bucket VARCHAR(255),
    image_object_key VARCHAR(1024),
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_event_blocks_event_id_position UNIQUE (event_id, position)
);

CREATE INDEX idx_events_status_updated_at
    ON events (status, updated_at DESC);

CREATE INDEX idx_event_blocks_event_id_position
    ON event_blocks (event_id, position);
