CREATE TABLE elements
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_json JSONB NOT NULL
);

CREATE TABLE rarities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_json JSONB   NOT NULL,
    stars     INTEGER NOT NULL,
    CONSTRAINT uq_rarities_stars UNIQUE (stars)
);

CREATE TABLE families
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_json        JSONB NOT NULL,
    description_json JSONB
);

CREATE TABLE mana_speeds
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_json        JSONB NOT NULL,
    description_json JSONB
);

CREATE TABLE alpha_talents
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_json        JSONB NOT NULL,
    description_json JSONB
);

CREATE TABLE hero_classes
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_json               JSONB NOT NULL,

    base_name_json          JSONB NOT NULL,
    base_description_json   JSONB NOT NULL,

    master_name_json        JSONB NOT NULL,
    master_description_json JSONB NOT NULL
);

CREATE TABLE hero_class_emblem_bonus_profiles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_class_id BIGINT REFERENCES hero_classes (id) NOT NULL,

    path_type     VARCHAR(50)                         NOT NULL,
    attack_bonus  INTEGER                             NOT NULL,
    armor_bonus   INTEGER                             NOT NULL,
    hp_bonus      INTEGER                             NOT NULL,
    CONSTRAINT uq_hero_class_emblem_bonus_profiles UNIQUE (hero_class_id, path_type)
);

CREATE TABLE rarity_evolution_multipliers
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rarity_id         BIGINT REFERENCES rarities (id) NOT NULL,

    stage_code        VARCHAR(50)                     NOT NULL,
    attack_multiplier NUMERIC(6, 4)                   NOT NULL,
    armor_multiplier  NUMERIC(6, 4)                   NOT NULL,
    hp_multiplier     NUMERIC(6, 4)                   NOT NULL,
    CONSTRAINT uq_rarity_evolution_multipliers UNIQUE (rarity_id, stage_code)
);

CREATE TABLE heroes
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                           VARCHAR(150)                        NOT NULL UNIQUE,

    name_json                      JSONB                               NOT NULL,
    special_skill_name_json        JSONB                               NOT NULL,
    special_skill_description_json JSONB                               NOT NULL,

    base_attack                    INTEGER,
    base_armor                     INTEGER,
    base_hp                        INTEGER,

    element_id                     BIGINT REFERENCES elements (id)     NOT NULL,
    rarity_id                      BIGINT REFERENCES rarities (id)     NOT NULL,
    hero_class_id                  BIGINT REFERENCES hero_classes (id) NOT NULL,
    family_id                      BIGINT REFERENCES families (id),
    mana_speed_id                  BIGINT REFERENCES mana_speeds (id)  NOT NULL,
    alpha_talent_id                BIGINT REFERENCES alpha_talents (id),

    image_bucket                   VARCHAR(100),
    image_object_key               VARCHAR(500),

    is_costume                     BOOLEAN                             NOT NULL DEFAULT FALSE,
    base_hero_id                   BIGINT REFERENCES heroes (id),
    costume_bonus_json             JSONB,

    release_date                   DATE,
    status                         VARCHAR(30)                         NOT NULL,

    created_at                     TIMESTAMP WITH TIME ZONE            NOT NULL,
    updated_at                     TIMESTAMP WITH TIME ZONE            NOT NULL,
    updated_by                     VARCHAR(100)                        NOT NULL
);

CREATE TABLE passive_skills
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_json        JSONB NOT NULL,
    description_json JSONB NOT NULL
);

CREATE TABLE heroes_passive_skills
(
    hero_id          BIGINT REFERENCES heroes (id)         NOT NULL,
    passive_skill_id BIGINT REFERENCES passive_skills (id) NOT NULL,
    PRIMARY KEY (hero_id, passive_skill_id)
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_heroes_name_ru_trgm
    ON heroes
        USING GIN (LOWER(name_json ->> 'ru') gin_trgm_ops);

CREATE INDEX idx_heroes_name_en_trgm
    ON heroes
        USING GIN (LOWER(name_json ->> 'en') gin_trgm_ops);